# Generated by Django 5.2.8 on 2025-12-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='test.jpg', upload_to='image'),
        ),
    ]
