# Generated by Django 6.0 on 2026-01-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categeory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='cat_image')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='pro_image')),
                ('categeory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categeory')),
            ],
        ),
    ]
