# Generated by Django 5.2.8 on 2025-12-11 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cat_alter_product_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat',
            new_name='catt',
        ),
        migrations.AddField(
            model_name='product',
            name='catt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.catt'),
        ),
    ]
